name: FirstAction

on: 
   push:
        branches: 
        - master
jobs:
      test:
       runs-on: ubuntu-latest
       steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: install Java
         uses: actions/setup-java@v4.7.0
         with:
             distribution: 'oracle'
             java-version: '21'
             cache: 'maven'
             cache-dependency-path: 'pom.xml' # optional
       - name: Build
         run: mvn clean install
       - name: ssh scp ssh pipelines
       - name: Установка SSH-ключа
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H "${{ secrets.IP_ADDR }}" >> ~/.ssh/known_hosts
       - name: Передача файлов
         run: |
           scp -r ./target/ROOT.war "${{ secrets.ACCOUNT }}"@"${{ secrets.IP_ADDR }}":/home/alexander/
