name: FirstAction

on: 
   push:
        branches: 
        - master
jobs:
      test:
       runs-on: ubuntu-latest
       steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: install Java
         uses: actions/setup-java@v4.7.0
         with:
             distribution: 'oracle'
             java-version: '21'
             cache: 'maven'
             cache-dependency-path: 'pom.xml' # optional
       - name: Build
         run: mvn clean install
       - name: ssh scp ssh pipelines
         uses: cross-the-world/ssh-scp-ssh-pipelines@latest
         with:
          host: ${{ secrets.IP_ADDR }}
          user: ${{ secrets.ACCOUNT }}
          pass: ${{ secrets.SSH_KEY }}
          port: 22
          first_ssh: |           
           ls -la 
          scp: |
                './ROOT.war*' => /home/alexander/
