name: FirstAction

on: 
   push:
        branches: 
        - master
jobs:
      test:
       runs-on: ubuntu-latest
       steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: install Java
         uses: actions/setup-java@v4.7.0
         with:
             distribution: 'oracle'
             java-version: '21'
             cache: 'maven'
             cache-dependency-path: 'tomcat-root-war/pom.xml' # optional
       - name: Build
         run: mvn clean install
