name: FirstAction

on: 
   push:
        branches: 
        - master
jobs:
      test:
       runs-on: ubuntu-latest
       steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: install Java
         uses: actions/setup-java@v4.7.0
