name: FirstAction

on: 
   push:
        branches: 
        - master
jobs:
      test:
       runs-on: ubuntu-latest
       steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: install Java
         uses: actions/setup-java@v4.7.0
         with:
             distribution: 'oracle'
             java-version: '21'
             cache: 'maven'
             cache-dependency-path: 'pom.xml' # optional
       - name: Build
         run: mvn clean install
       - name: ssh scp ssh pipelines
         uses: betanzos/scp-upload@v1
         with:
          sourse: "./target/ROOT.war"
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.ACCOUNT }}
          key: ${{ secrets.SSH_KEY }}
        #  remote_dir: 
